CREATE TABLE IF NOT EXISTS user_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id VARCHAR(64) NOT NULL UNIQUE,
  music_language VARCHAR(30) NOT NULL,
  favorite_genre VARCHAR(50) NOT NULL,
  kpop_group VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE mood_entries ADD COLUMN IF NOT EXISTS visitor_id VARCHAR(64);
ALTER TABLE mood_entries ADD COLUMN IF NOT EXISTS mood_text TEXT;
ALTER TABLE mood_entries ADD COLUMN IF NOT EXISTS diary_text TEXT;

CREATE INDEX IF NOT EXISTS idx_mood_entries_visitor_created
ON mood_entries (visitor_id, created_at DESC);
