CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  display_name VARCHAR(80),
  password_hash VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id VARCHAR(64) NOT NULL UNIQUE,
  music_language VARCHAR(30) NOT NULL,
  favorite_genre VARCHAR(50) NOT NULL,
  kpop_group VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mood_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  visitor_id VARCHAR(64),
  mood VARCHAR(20) NOT NULL,
  listening_context VARCHAR(20) NOT NULL,
  mood_text TEXT,
  diary_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_mood_entries_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_mood_entries_visitor_created
ON mood_entries (visitor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS song_inputs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mood_entry_id BIGINT NOT NULL,
  itunes_track_id VARCHAR(64),
  track_name VARCHAR(255) NOT NULL,
  artist_name VARCHAR(255) NOT NULL,
  album_name VARCHAR(255),
  genre VARCHAR(120),
  artwork_url TEXT,
  preview_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_song_inputs_entry
    FOREIGN KEY (mood_entry_id) REFERENCES mood_entries(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS analysis_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mood_entry_id BIGINT NOT NULL,
  song_input_id BIGINT NOT NULL,
  temperature INTEGER NOT NULL,
  drift_need VARCHAR(20) NOT NULL,
  music_profile VARCHAR(255) NOT NULL,
  analysis_text TEXT NOT NULL,
  suggestion_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_analysis_results_entry
    FOREIGN KEY (mood_entry_id) REFERENCES mood_entries(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_analysis_results_song
    FOREIGN KEY (song_input_id) REFERENCES song_inputs(id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS favorite_songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id VARCHAR(64),
  itunes_track_id VARCHAR(64),
  track_name VARCHAR(255) NOT NULL,
  artist_name VARCHAR(255) NOT NULL,
  album_name VARCHAR(255),
  genre VARCHAR(120),
  artwork_url TEXT,
  preview_url TEXT,
  apple_music_url TEXT,
  youtube_music_url TEXT,
  spotify_url TEXT,
  soundcloud_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_favorite_song UNIQUE(visitor_id, track_name, artist_name)
);
